**numPy**

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a*b

array([ 5, 12, 21, 32])

In [6]:
type(a)

numpy.ndarray

In [14]:
np.array([3.14,4,5,6], dtype=int)

array([3, 4, 5, 6])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [22]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
np.random.normal(10,4,(3,4))

array([[ 5.45643944,  6.51004051,  4.49920294, 12.79426908],
       [ 9.201649  , 11.85569166, 11.27918033,  5.2050277 ],
       [ 7.4780066 , 14.42188281,  5.24211442, 13.0896793 ]])

In [28]:
np.random.randint(0,10,(3,3))

array([[1, 2, 9],
       [1, 0, 6],
       [4, 6, 1]])

**ndim = number of dimension**

**shape = dimensions of the array**

**size = total number of elements**

**dtype = data type of the elements**

In [34]:
a = np.random.randint(0,10,size=10)
a

array([6, 3, 5, 5, 9, 1, 8, 3, 1, 2])

In [36]:
a.ndim

1

In [38]:
a.shape

(10,)

In [42]:
b = np.random.randint(10,size=(3,5))
b

array([[6, 8, 1, 2, 6],
       [3, 2, 3, 5, 0],
       [5, 6, 3, 3, 4]])

In [44]:
b.size

15

**reshaping**

In [50]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**concatenation**

In [55]:
a = np.array([[1,2,3],
              [4,5,6]]) #two dimensions

In [61]:
np.concatenate([a,a], axis=1) #axis=1 column

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**splitting**

In [64]:
a = np.array([1,2,77,89,4,56,23])
np.split(a,[3,5])

[array([ 1,  2, 77]), array([89,  4]), array([56, 23])]

In [66]:
a,b,c = np.split(a,[3,5])
b

array([89,  4])

In [68]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

**indexing**

In [77]:
m[1,0]

4

**Fancy indexing** in NumPy refers to using an array of integers or boolean masks to select specific elements from another array.

In [80]:
arr = np.array([10, 20, 30, 40, 50])

indices = [1, 3, 4]
result = arr[indices]
result

array([20, 40, 50])

In [82]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

row_indices = [0, 2]
result = arr[row_indices]
result

array([[10, 20, 30],
       [70, 80, 90]])

**pandas**

In [85]:
import pandas as pd

In [93]:
a = pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [95]:
a.axes

[RangeIndex(start=0, stop=5, step=1)]

In [97]:
a.dtype

dtype('int64')

In [99]:
a.size

5

In [101]:
a.values

array([1, 2, 3, 4, 5], dtype=int64)

In [105]:
a.head(3)

0    1
1    2
2    3
dtype: int64

In [107]:
pd.Series([12,34,56,67,89], index=["a","b","c","d","e"])

a    12
b    34
c    56
d    67
e    89
dtype: int64

In [109]:
a.keys

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

**dataFrame**

In [112]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [25, 30, 35, 40],
    "city": ["New York", "Los Angeles", "Chicago", "Houston"]
}

df = pd.DataFrame(data)
df

name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [114]:
df.items

<bound method DataFrame.items of       name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston>

In [120]:
df.shape

(4, 3)

In [126]:
drp = df.drop(index=0)
drp

name  age         city
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [128]:
df.drop(index=0, inplace=True) #permanently dropping
df

name  age         city
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In pandas, **iloc[]** and **loc[]** are used for indexing and selecting data from a DataFrame.

iloc[] (Integer Location)

loc[] (Label-based Location)

In [132]:
df.iloc[0, 1]

30

In [140]:
df.loc[1, "age"]

30

In [142]:
df.loc[:, "name"]

1        Bob
2    Charlie
3      David
Name: name, dtype: object

The **concat()** function is used to concatenate two or more DataFrames along a particular axis (either rows or columns). It can concatenate along rows (axis=0) or columns (axis=1).

In [145]:
df2 = pd.DataFrame({
    "name": ["David", "Eve"],
    "age": [40, 45],
    "city": ["Houston", "Phoenix"]
})
result = pd.concat([df, df2])
result

name  age         city
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
0    David   40      Houston
1      Eve   45      Phoenix

**Merge()** function is used to combine two DataFrames based on a common column or index.

In [148]:
df1 = pd.DataFrame({
    "EmployeeID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40]
})

df2 = pd.DataFrame({
    "EmployeeID": [1, 2, 4],
    "Department": ["HR", "Engineering", "Finance"]
})

merged_df = pd.merge(df1, df2, on="EmployeeID", how="inner") #inner join
merged_df

EmployeeID   Name  Age   Department
0           1  Alice   25           HR
1           2    Bob   30  Engineering
2           4  David   40      Finance

**aggregation and grouping**

In [151]:
import seaborn as sns

In [155]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [157]:
df.shape

(1035, 6)

In [159]:
df["mass"].mean()

2.6381605847953216

In [161]:
df["mass"].count()

513

In [165]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [167]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

**groupby**

In [174]:
grouped_mean = df.groupby("method")[["orbital_period", "year"]].mean()
print("\nMean of orbital_period and year by method:")
print(grouped_mean)

grouped_count = df.groupby(["method", "year"])["orbital_period"].count()
print("\nCount of planets by method and year:")
print(grouped_count)

grouped_total_planets = df.groupby("year")["orbital_period"].count()
print("\nTotal number of planets discovered by year:")
print(grouped_total_planets)

grouped_sum_orbital = df.groupby("method")["orbital_period"].sum()
print("\nSum of orbital_period by method:")
print(grouped_sum_orbital)


Mean of orbital_period and year by method:
                               orbital_period         year
method                                                    
Astrometry                         631.180000  2011.500000
Eclipse Timing Variations         4751.644444  2010.000000
Imaging                         118247.737500  2009.131579
Microlensing                      3153.571429  2009.782609
Orbital Brightness Modulation        0.709307  2011.666667
Pulsar Timing                     7343.021201  1998.400000
Pulsation Timing Variations       1170.000000  2007.000000
Radial Velocity                    823.354680  2007.518987
Transit                             21.102073  2011.236776
Transit Timing Variations           79.783500  2012.500000

Count of planets by method and year:
method                     year
Astrometry                 2010     1
                           2013     1
Eclipse Timing Variations  2008     2
                           2009     1
                          